apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql-pod
spec:
  containers:
    - name: mysql-container
      image: mysql:8.0
      ports:
        - containerPort: 3306
      env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "123456"
        - name: "MYSQL_DATABASE"
          value: bd_teste
        - name: "MYSQL_PASSWORD"
          value: "123456"